version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10.13@sha256:991bcf4d64fb0038ba55dc0660f9ecd2dc4482bcdf5197fa99df360e28b9fe3e
    working_directory: /tmp/trading-card-manager

jobs:
  gitclone:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: 'Recovering Secrets'
          command: sh ./.circleci/restore-secrets.sh
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths: .
  build:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Print files on file system'
          command: ls -la
      - run:
          name: 'Npm Install'
          command: make web_install
      - run:
          name: 'Build'
          command: make web_build
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths: .
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'CI Check'
          command: make web_ci-check
      - run:
          name: 'Sonar'
          command: make web_sonar-scanner
      - store_artifacts:
          path: web/coverage
          prefix: web/coverage

  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Deploy'
          command: make web_deploy

workflows:
  version: 2.1
  build_and_test-web:
    jobs:
      - gitclone:
          context: mtgx-web-context
      - build:
          requires:
            - gitclone
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
