version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13@sha256:991bcf4d64fb0038ba55dc0660f9ecd2dc4482bcdf5197fa99df360e28b9fe3e
    working_directory: ~/trading-card-manager
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: 'NPM INSTALL'
          command: make web_install
      - save_cache:
          paths:
            - web/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'CI CHECK'
          command: make web_ci-check
      - run:
          name: 'Sonar'
          command: make web_sonar-scanner
      - store_artifacts:
          path: web/coverage
          prefix: web/coverage
