version: 2.1

executors:
  sonar-scaner:
    docker:
      - image: eduardomoroni/sonar-scanner:ALPHA
    working_directory: /tmp/trading-card-manager
  frontend:
    environment:
      - CI: true
    docker:
      - image: circleci/node:10.13@sha256:991bcf4d64fb0038ba55dc0660f9ecd2dc4482bcdf5197fa99df360e28b9fe3e
    working_directory: /tmp/trading-card-manager/web
  backend:
    environment:
      - CI: true
    docker:
      - image: circleci/node:6.11
    working_directory: /tmp/trading-card-manager/backend

jobs:
  gitclone:
    working_directory: /tmp/trading-card-manager
    executor: frontend
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths:
            - web
            - core

  build-frontend:
    executor: frontend
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Npm Install'
          command: make install
      - run:
          name: 'Build'
          command: make build
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths:
            - web
            - core

  test-frontend:
    executor: frontend
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'CI Check'
          command: make ci-check
      - store_artifacts:
          path: coverage
          prefix: coverage
#      - persist_to_workspace:
#          root: /tmp/trading-card-manager
#          paths:
#            - web
#            - core
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths: web/coverage

  sonar-frontend:
    executor: sonar-scaner
    working_directory: /tmp/trading-card-manager/web
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Sonar'
          command: make web_sonarqube

  deploy-frontend:
    executor: frontend
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Deploy'
          command: make deploy

  test-backend:
    executor: backend
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'CI Check'
          command: make ci-check
      - store_artifacts:
          path: coverage
          prefix: coverage
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths: backend/coverage

  sonar-backend:
    executor: sonar-scaner
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Sonar'
          command: make backend_sonarqube

  deploy-backend:
    executor: backend
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Deploy'
          command: make deploy

workflows:
  version: 2.1
  Frontend-Build-Pipeline:
    jobs:
      - gitclone
      - build-frontend:
          requires:
            - gitclone
      - test-frontend:
          requires:
            - build-frontend
      - sonar-frontend:
          context: mtgx-web-context
          requires:
            - test-frontend
      - deploy-frontend:
          context: mtgx-web-context
          requires:
            - test-frontend
          filters:
            branches:
              only:
                - master
  Backend-Build-Pipeline:
    jobs:
      - gitclone
      - test-backend:
          requires:
            - gitclone
      - sonar-backend:
          context: mtgx-web-context
          requires:
            - test-backend
      - deploy-backend:
          context: mtgx-web-context
          requires:
            - test-backend
          filters:
            branches:
              only:
                - master
