version: 2.1

executors:
  sonar-scaner:
    docker:
      - image: eduardomoroni/sonar-scanner:ALPHA
    working_directory: /tmp/trading-card-manager/web
  main:
    docker:
      - image: circleci/node:10.13@sha256:991bcf4d64fb0038ba55dc0660f9ecd2dc4482bcdf5197fa99df360e28b9fe3e
    working_directory: /tmp/trading-card-manager/web

jobs:
  gitclone:
    working_directory: /tmp/trading-card-manager
    executor: main
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths:
            - web
            - core

  build:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Npm Install'
          command: make install
      - run:
          name: 'Build'
          command: make build
      - persist_to_workspace:
          root: /tmp/trading-card-manager
          paths:
            - web
            - core

  sonar:
    executor: sonar-scaner
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Sonar'
          command: make sonarqube

  test:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'CI Check'
          command: make ci-check
      - store_artifacts:
          path: coverage
          prefix: coverage
      - persist_to_workspace:
          root: /tmp/trading-card-manager/web
          paths: coverage

  deploy:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/trading-card-manager
      - run:
          name: 'Deploy'
          command: make deploy

workflows:
  version: 2.1
  build_and_test-web:
    jobs:
      - gitclone
      - build:
          requires:
            - gitclone
      - test:
          requires:
            - build
#      - sonar:
#          context: mtgx-web-context
#          requires:
#            - test
      - deploy:
          context: mtgx-web-context
          requires:
            - test
          filters:
            branches:
              only:
                - master
