version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/trading-card-manager
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: make web_install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: make web_ci-check
      - run: make sonar-scanner
