install:
  - nvm install && nvm use
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
  - yarn install
matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
        - yes | sdkmanager "platforms;android-26"
      script:
        - "./android/gradlew assembleRelease -p android/"
    - os: osx
      osx_image: xcode9.3
      before_install:
        - gem install bundler -v 2.0.1
        - brew install jq
        - bundle install
      script:
        - bundle exec fastlane ios test
